# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='commit',
            name='committer',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
